version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: "elabx_db" 
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "elabx_db"
      MYSQL_USER: "elabx"
      MYSQL_PASSWORD: "elabx_password"
      MYSQL_ROOT_PASSWORD: "root"

    volumes:
      - ./data/mysql:/var/lib/mysql

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    
    container_name: "elabx_server"

    ports:
      - "8000:8000"
    depends_on:
      - db

  client:
    build:
      context: ./client/elabx
      dockerfile: Dockerfile

    container_name: "elabx_client"
    ports:
      - 80:80
    depends_on:
      - server
