version: "3"

services:

  client:
    build:
      context: ./client/app
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8000:8000

